pipeline:
  build:
    image: docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker build
        --label org.label-schema.vcs-ref=$DRONE_COMMIT_SHA
        --label build-number=$DRONE_BUILD_NUMBER
        --label build-date="$(date)"  
        -t dark13side/example-webserver:$DRONE_COMMIT_SHA .

  test:
    image: docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      -  docker run dark13side/example-webserver:$DRONE_COMMIT_SHA /test.sh

  push:
    image: docker
    environment:
      - PASS=${HUB_PASS}
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker login -u dark13side -p $PASS
      - docker push dark13side/example-webserver:$DRONE_COMMIT_SHA

  deploy:
    image: docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker pull dark13side/example-webserver:$DRONE_COMMIT_SHA
      - docker tag dark13side/example-webserver:$DRONE_COMMIT_SHA dark13side/example-webserver:production
      - docker stack deploy -c ./docker-compose.yml example-webserver
